### ISSUE TITLE
undefined: js.Wrapper

### ISSUE THREAD

**Issue by ra-app** [nlepage/go-wasm-http-server#7]
hi, trying to run the hello example.

In go-wasm-http-server/docs/hello

GOOS=js GOARCH=wasm go build -o api.wasm .

but i am stuck here:

../../response_recorder.go:19:10: undefined: js.Wrapper

**Comment by norbjd** [comment]
Hello :wave: 

I just faced the same error, `Wrapper` is not available anymore in go 1.18 (https://pkg.go.dev/syscall/js@go1.18).

But it works with go 1.17 (https://pkg.go.dev/syscall/js@go1.17).

**Comment by nlepage** [comment]
Hi @ra-app 

Just published a v1.1.0 to fix this.
I rebuilt the examples with go 1.18 and it works fine: https://nlepage.github.io/go-wasm-http-server/hello/
Please fetch the latest sources and let me know if it is OK for you.

Be aware that the library does not import the [`wasm_exec.js` script](https://github.com/golang/go/blob/462b78fe7027ef0d2e2b40c3cfd1f5a37d307310/misc/wasm/wasm_exec.js) anymore, so it must be done in the service worker, see this example:
https://github.com/nlepage/go-wasm-http-server/blob/163b49702b99178974488f1ae9f9e9dde56d7cd8/docs/hello/sw.js
